#!/usr/bin/env bash

set -e

if [ ! -p /dev/stdin ]; then
	echo "usage: ... | $0"
	echo "provide hours in list with pipe"
	echo "ex. ## yyyy-mm-dd:tttt-tttt PROJECT_ID TASK_ID DESCRIPTION\n"
	exit 1
fi

while read -r piped_line; do
	IFS=' ' read -ra line <<< "$piped_line"
	ARRAY=("$line")

	if [ ${#line[@]} -lt 5 ]; then
		echo "provided ${line[@]}"
		exit 1
	fi

	DATE_TIME_RANGE=${line[1]}
	PROJECT=${line[2]}
	TASK=${line[3]}

	DESCRIPTION=""
	for (( i=4; i<${#line[@]}; i++ ));
	do
		if [ $i -gt 4 ];then
			DESCRIPTION+=" "
		fi
			DESCRIPTION+=$(echo "${line[$i]}")
	done

	PARSED="$(parse-hours $DATE_TIME_RANGE)"
	ARGS=($PARSED)

	DATE="${ARGS[0]}"
	START="${ARGS[1]}"
	END="${ARGS[2]}"

	add-hours $PROJECT $TASK $DATE $START $END "$DESCRIPTION"
done