#!/usr/bin/env bash

# set -e

if [ "$#" -ne 1 ]; then
    echo "usage: $0 <file>"
    echo "given: $0 $@"
    exit 1
fi

BREAK="\-\-\-"
H2="##"
PUNCHCARD_REGEX="[0-9]{4}-[0-9]{2}-[0-9]{2}:[0-9]{4}-[0-9]{4}"
FILE=$1


LAST_WEEKS_PUNCHCARDS=$(tac $FILE | grep -m1 -B 9999 "$BREAK" | grep "$H2")
BAD_FORMAT_PUNCHCARDS=$(echo "$LAST_WEEKS_PUNCHCARDS" | grep -Ev "$PUNCHCARD_REGEX")

$BAD_FORMAT_PUNCHCARDS 2>/dev/null
if [ $? != 0 ]; then
    echo -e "bad hour formatting:\n$BAD_FORMAT_PUNCHCARDS"
    exit 1
fi

BAD_YEAR_PUNCHCARDS=$(echo "$LAST_WEEKS_PUNCHCARDS" | grep "2022")

$BAD_YEAR_PUNCHCARDS 2>/dev/null
if [ $? != 0 ]; then
    echo -e "bad year:\n$BAD_YEAR_PUNCHCARDS"
    exit 1
fi

echo "$LAST_WEEKS_PUNCHCARDS" | grep -E "$PUNCHCARD_REGEX"