#!/usr/bin/env bash


set -e

if [ "$#" -ne 1 ]; then
	echo "usage: $0 <date-timerange>"
	echo "given $0 $@"
	echo "provide date with start and end time in format ## yyyy-mm-dd:tttt-tttt"
	echo "outputs yyyy-mm-dd tttt tttt"
	exit 1
fi

# remove prefix of ##\w
PREFIX="## "
DATE_TIMERANGE=${1#"$PREFIX"}

# split date from time range
IFS=':'
read -a DATE_AND_TIMERANGE <<< "$DATE_TIMERANGE"
if [ ${#DATE_AND_TIMERANGE[@]} -ne 2 ]; then
	echo "provided date-timerange does not follow format"
	exit 1
fi

DATE=${DATE_AND_TIMERANGE[0]}
TIMERANGE=${DATE_AND_TIMERANGE[1]}

# split start and end time
IFS="-"
read -a START_AND_END_TIME <<< "$TIMERANGE"
if [ ${#START_AND_END_TIME[@]} -ne 2 ]; then
	echo "provided timerange does not follow format"
	exit 1
fi

START=${START_AND_END_TIME[0]}
END=${START_AND_END_TIME[1]}

echo "$DATE $START $END"