#!/usr/bin/env bash


set -e

if [ "$#" -lt 6 ]; then
	echo "usage: $0 <project> <task> <date> <start> <end> <description>"
	echo "given: $0 $@"
	echo "provide \"project\" \"task\" yyyy-mm-dd tttt tttt"
	exit 1
elif [ ${#4} -ne 4 ]; then
	echo "start time does not follow format"
	echo "$4 should follow tttt"
	exit 1
elif [ ${#5} -ne 4 ]; then
	echo "end time does not follow format"
	echo "$4 should follow tttt"
	exit 1
fi

PROJECT=$1
TASK=$2
DATE=$3
DESCRIPTION=$6

STARTTIME=${4:0:2}:${4:2:2}
ENDTIME=${5:0:2}:${5:2:2}

START="$DATE $STARTTIME"
END="$DATE $ENDTIME"

clockify-cli manual \
 --interactive=0 \
 --project="$PROJECT" --task="$TASK" \
 --when="$START" --when-to-close="$END" \
 --description="$DESCRIPTION"