#!/usr/bin/env bash

set -e

PROJECT_PHASE_2="5f91ec0fb1d41c38c2d6719b"
PROJECT_PHASE_2_MEETINGS="5f47d5879d6dc04fbfedcdab"
TASK_MEETINGS="6109a1f50a335f28d1599ef3"

fn_exists() {
  [ `type -t $1`"" == 'function' ]
}

get_phase_2_tasks() {
    clockify-cli --project="$PROJECT_PHASE_2" tasks list --json | jq .
}

get_phase_2_tasks_active() {
    get_phase_2_tasks | jq '[.[] | select(.status=="ACTIVE")]'
}

get_phase_2_tasks_active_id() {
    get_phase_2_tasks_active | jq '[.[] | "\(.name), \(.id), \(.projectId)"]'
}

get_phase_2_meeting_tasks() {
    clockify-cli --project="$PROJECT_PHASE_2_MEETINGS" tasks list --json | jq .
}

get_phase_2_meeting_tasks_active() {
    get_phase_2_meeting_tasks | jq '[.[] | select(.status=="ACTIVE")]'
}

get_phase_2_meeting_tasks_active_id() {
    get_phase_2_meeting_tasks_active | jq '[.[] | "\(.name), \(.id), \(.projectId)"]'
}

sub_get_phase_2_tasks() {
    get_phase_2_tasks
}

sub_get_phase_2_tasks_active() {
    get_phase_2_tasks_active
}

sub_get_phase_2_tasks_active_id() {
    get_phase_2_tasks_active_id
}

sub_get_phase_2_meeting_tasks() {
    get_phase_2_meeting_tasks
}

sub_get_phase_2_meeting_tasks_active() {
    get_phase_2_meeting_tasks_active
}

sub_get_phase_2_meeting_tasks_active_id() {
    get_phase_2_meeting_tasks_active_id
}

sub_help(){
    echo "Usage: $0 <subcommand> <variables>"
    echo ""
    echo "Subcommands:    Parameters:              Description:"
    echo " get_phase_2_tasks"
    echo " get_phase_2_tasks_active"
    echo " get_phase_2_tasks_active_id"
    echo " get_phase_2_meeting_tasks"
    echo " get_phase_2_meeting_tasks_active"
    echo " get_phase_2_meeting_tasks_active_id"
    echo ""
}

subcommand=$1
case $subcommand in
    "" | "-h" | "--help")
        sub_help
        ;;
    *)
        shift
        if ! fn_exists sub_${subcommand}; then
            echo "Error: '$subcommand' is not an subcommand"
            exit 1
        fi

        sub_${subcommand} $@
        ;;
esac
